### ISSUE TITLE
Annotate page gets weird

### ISSUE THREAD

**Issue by Slamdunk** [refined-bitbucket/refined-bitbucket#214] opened 2018-05-17 09:28 UTC
Hi, using the extension version 3.8.0 on Firefox 60 (but I always had this issue) the annotate page gets weird line alignment:

### Without the extension

![rb-before](https://user-images.githubusercontent.com/152236/40169008-48bd7c88-59c5-11e8-971b-6443331620af.png)

### With Refined Bitbucket

![rb-after](https://user-images.githubusercontent.com/152236/40169026-526336c4-59c5-11e8-8b92-49e203e3cf4e.png)

The `pre` tag gets a font-size that alters the alignment with the annotations and becomes unreadable.

I think annotate page shouldn't need any change.

**Comment by reyronald** [comment] 2018-05-17 12:57
Hello @Slamdunk ,

All of the features of the extension are opt-in, if there's any that's causing you trouble, you can go to the Options page and disable them. In this case, you should disable the "Improve fonts..." and it should be back to normal. Let me know how it goes.

Also, I think this is a duplicate of #199

**Closed as completed by reyronald** 2018-05-17 12:57 UTC
