### ISSUE TITLE
Inline code in comments look different when Syntax Highlighting is enabled on Google Chrome

### ISSUE THREAD

**Issue by AndyDeany** [refined-bitbucket/refined-bitbucket#74] opened 2017-11-06 14:49 UTC
When _Syntax Hightlighing_ is enabled, inline code in comments, `like this`, do not have a background as they do ordinarily.

Syntax highlighting enabled:
![](https://image.prntscr.com/image/GKFR_IMJRc6g-OjJzBYjRA.png)

Syntax highlighting disabled:
![](https://image.prntscr.com/image/ZJVV16yRSReUVgKiSPpA8Q.png)

Some info about my Chrome:

Google Chrome | 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 57c9d07b416b5a2ea23d28247300e4af36329bdc-refs/branch-heads/3163@{#1250}
OS | Windows
JavaScript | V8 6.1.534.41
Flash | 27.0.0.183 C:\Users\andrewdean\AppData\Local\Google\Chrome\User Data\PepperFlash\27.0.0.183\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by reyronald** [comment] 2018-01-05 18:16
Duplicate of #93

**Closed as completed** 2018-01-05 18:51 UTC
Labels: duplicate, enhancement

**Comment by reyronald** [comment] 2018-01-09 13:33
This should be solved in the already published release v3.3.0. Let me know!

**Comment by AndyDeany** [comment] 2018-01-10 20:12
Yes, I can confirm it's working now :) thanks
