### ISSUE TITLE
Error while parsing TypeScript React (tsx)

### ISSUE THREAD

**Issue by atdrago** [refined-bitbucket/refined-bitbucket#151] opened 2018-02-13 17:10 UTC
Just wanted to report this because I ran across it this morning. I noticed I wasn't getting syntax highlighting for a certain TSX file and found this error in my console:

```
refined-bitbucket(code-review):  TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at u (chrome-extension://afppminkfnfngihdocacbgeajbbdklkf/main.js:1)
    at HTMLElement.<anonymous> (chrome-extension://afppminkfnfngihdocacbgeajbbdklkf/main.js:1)
    at chrome-extension://afppminkfnfngihdocacbgeajbbdklkf/main.js:1
    at Array.forEach (<anonymous>)
    at p (chrome-extension://afppminkfnfngihdocacbgeajbbdklkf/main.js:1)
    at chrome-extension://afppminkfnfngihdocacbgeajbbdklkf/main.js:1
    at Array.forEach (<anonymous>)
    at new a (chrome-extension://afppminkfnfngihdocacbgeajbbdklkf/main.js:1)
    at HTMLDivElement.Element.observeSelector (chrome-extension://afppminkfnfngihdocacbgeajbbdklkf/main.js:1)
    at t.then.t (chrome-extension://afppminkfnfngihdocacbgeajbbdklkf/main.js:1)
```

I cleared my cache and refreshed multiple times with no change. This isn't happening with all TSX files, so I'll look into exactly what is causing this when I have some time.

**Comment by reyronald** [comment] 2018-02-13 22:04
Hm, that's odd :/, never seen that one before. Is the error consistent? Meaning, does it always fail with the same files every time ?

I've done several refactors to the entire code base in recent releases so it's possible I broke something =(. Did you make sure you are not running both the dev and the production extension at the same time, by the way ?

**Comment by atdrago** [comment] 2018-02-22 18:47
Just wanted to pop in so this doesn't get stale. I still haven't had time to look into it, but just to answer your questions:

- I believe the error is consistent in that it occurs for the same file
- Yes, I did check that I wasn't running both versions. I was running the live 3.6.0 and had the local version disabled

If I'm able to pinpoint what's causing it just through normal PR review, I'll definitely update this. Otherwise, my deadlines are so tight right now that I won't be able to provide anything meaningful to you anytime soon. If you want to close this in the mean time, that's fine, but I do plan on looking at this

**Comment by reyronald** [comment] 2018-02-22 19:17
Hey @atdrago , thanks for stopping by! And don't worry, I won't close it because I'm interested myself in getting this resolved, apparently it has popped up to other users as well, see #152 !

I haven't encountered this myself yet so I can't help much, but I was doing some digging regardless and I think the issue relies here specifically: https://github.com/refined-bitbucket/refined-bitbucket/blob/dev/src/syntax-highlight/syntax-highlight.js#L46-L47. Apparently there are some instances where the `div.refract-content-container` is not loaded in time for the extension to pick it up when it gets to that point, or something similar...

I would suggest that you run the local development version and modify those lines as follows:

```diff
const codeContainer = diff.querySelector('.refract-content-container');
+
+if (!codeContainer) {
+  debugger;
+  console.log(diff);
+}
+
codeContainerObserver.observe(codeContainer, { childList: true });
```

Then, if my intuition is correct, you should see the diff printed to the console when this happens and confirm if that's the case, and if it is, I think you could try this to see if it fixes it:

```diff
-const codeContainer = diff.querySelector('.refract-content-container');
+const codeContainer = await elementReady('.refract-content-container', { target: diff });
codeContainerObserver.observe(codeContainer, { childList: true });
```

I could be completely wrong, but it's a good start regardless. I'll be here if you need any help! Also, you can reach me quicker through Twitter since I get notified by those immediately, just in case you need some immediate assistance.

And again, thank you for your availability to help resolve this! 🙌

**Comment by reyronald** [comment] 2018-06-30 20:02
Closing this to decrease a little bit of the clutter on the open issues page and because I haven't been able to reproduce this myself. Feel free to re-open or comment if anyone has something else to add to the discussion!

**Closed as completed by reyronald** 2018-06-30 20:02 UTC

**Comment by yuritoledo** [comment] 2020-06-03 13:24
The highlight still does not work in TSX files :/
