### ISSUE TITLE
Extra leading "-" in some diff lines

### ISSUE THREAD

**Issue by davidmankin** [refined-bitbucket/refined-bitbucket#175] opened 2018-03-05 19:53 UTC
Refined Bitbucket is adding extra minuses at the start of some deleted lines.

See: 
![image](https://user-images.githubusercontent.com/721246/36996389-96b2f014-206b-11e8-9824-e1dea96c1bd1.png)

Some of the deleted lines end up with two minuses and some with one. 

The same diff without the extension:
![image](https://user-images.githubusercontent.com/721246/36996491-d56f0e82-206b-11e8-857d-df29e24ef886.png)

**Comment by reyronald** [comment] 2018-03-05 19:59
Hello @davidmankin , thanks for reporting the issue!

That's a bug in the "Don't carry pluses and minuses to clipboard when copying diff's contents" feature, if you disable it in the Options, your diff should return to normal.

I'm planning to have it fixed in the next release some time next week, sorry for the inconvenience!

**Comment by reyronald** [comment] 2018-03-08 12:55
Duplicate of #168

**Closed as completed** 2018-03-22 13:19 UTC
Labels: bug, duplicate
