### ISSUE TITLE
Options "Don't carry pluses and minuses" and "Syntax highlighting" cause missing leading plusses 

### ISSUE THREAD

**Issue by JimPatterson** [refined-bitbucket/refined-bitbucket#161] opened 2018-02-27 22:30 UTC
With the recent update to 3.7.0 I noticed that some of our code looked wrong.  Playing around with it, it looks like if both of the options "Don't carry pluses and minuses" and "Syntax highlighting" are on, then leading plus ("+") characters in the source code are hidden.   If either of those options are off, then the code shows correctly.

Look at line 85 in ![leading_plus-with_dont_carry_plus-off](https://user-images.githubusercontent.com/1703168/36758592-e659f19a-1be2-11e8-9ba3-f7293849a6e6.png)  You will see the leading "+" character under the "o" in "window".  This snippet is with the "Don't carry pluses and minuses" option off.

But in ![leading_plus-with_dont_carry_plus-on](https://user-images.githubusercontent.com/1703168/36758606-f2877154-1be2-11e8-954e-0442254682b0.png) that "+" is missing once the option is turned on.

**Comment by reyronald** [comment] 2018-02-27 23:53
Hello @JimPatterson , thank you for letting me know!

Could you provide me with the HTML of line 85 with the Syntax Highlighting option off? It would be a `<div class="udiff-line addition"> ... </div>`, that would help tremendously!

**Comment by JimPatterson** [comment] 2018-02-28 00:08
I captured both with the option on and off.  Here are the files for you.

BTW: Thanks for this extension, it helps a lot.

[option-on.txt](https://github.com/refined-bitbucket/refined-bitbucket/files/1765132/option-on.txt)
[option-off.txt](https://github.com/refined-bitbucket/refined-bitbucket/files/1765133/option-off.txt)

**Comment by reyronald** [comment] 2018-02-28 00:30
@JimPatterson are you on Chrome or Firefox ?

And you are welcome! ^^

**Comment by JimPatterson** [comment] 2018-02-28 01:33
Chrome (on linux if that matters)

**Comment by reyronald** [comment] 2018-02-28 13:26
Hey @JimPatterson , truth to be told, I couldn't actually reproduce the error on my end, but I published a fix for this feature that might have impacted the behavior you were seeing. Please update and let me know if the issue persists.

**Comment by anupshah** [comment] 2018-02-28 15:56
Hi. I noticed the original problem and saw a fix, which is great. However, unfortunately still seeing a problem with the latest version. See the two screenshots as examples in C# and SCSS

![image](https://user-images.githubusercontent.com/2446665/36797397-c096a404-1c9f-11e8-9af0-07d5e3a55ff5.png)
In the above, should see background-color and border-color. Instead see the first two characters missing

![2018-02-28_15h53_41](https://user-images.githubusercontent.com/2446665/36797443-dedc9194-1c9f-11e8-9b88-e5e09ebd038b.png)
In the above, which is C#, the first character of each line is missing...

Hope that helps.

**Comment by JimPatterson** [comment] 2018-02-28 16:41
It seems to have gotten worse.  That same section of code now looks like 
![more-missing-first-chars](https://user-images.githubusercontent.com/1703168/36794576-b3a84f9e-1c6e-11e8-8ee7-d23eeabf3bdf.png)  Notice the the "t" on line 86 is now missing.

The html for the lines is:
[86-good.txt](https://github.com/refined-bitbucket/refined-bitbucket/files/1767571/86-good.txt)
[85-good.txt](https://github.com/refined-bitbucket/refined-bitbucket/files/1767572/85-good.txt)
[86-broken.txt](https://github.com/refined-bitbucket/refined-bitbucket/files/1767573/86-broken.txt)
[85-broken.txt](https://github.com/refined-bitbucket/refined-bitbucket/files/1767574/85-broken.txt)

I'm working on setting up an repo that reproduces the problem.

**Comment by reyronald** [comment] 2018-02-28 17:03
@JimPatterson @anupshah I suggest you turn off the "Don't carry pluses and minuses to clipboard" in the mean time while I solve this, so that it doesn't affect your code review experience! I assume that you don't see that happening with the feature off, right?

**Comment by reyronald** [comment] 2018-02-28 17:05
@anupshah Could you provide me the HTML of the lines that are broken? It should be a `<div class="udiff-line addition"> ... </div>` node. Also, are you using the latest version of Chrome?

**Comment by reyronald** [comment] 2018-02-28 17:24
@anupshah @JimPatterson Nevermind, I already noticed what the problem is! Working on a fix now

**Closed as completed** 2018-02-28 19:54 UTC
Labels: bug

**Comment by reyronald** [comment] 2018-02-28 19:59
Just published a new release, please check again and let me know what do you see!

**Comment by JimPatterson** [comment] 2018-02-28 20:06
The updated version looks good.  Thanks for the super fast fix.

**Comment by anupshah** [comment] 2018-03-01 18:02
Hi. Thanks for such a quick turnaround. Faster than my ability to respond, that's for sure :)

Just checked and looks fixed to me!
