### ISSUE TITLE
Refined cases degradation of bitbucket user interface

### ISSUE THREAD

**Issue by theKashey** [refined-bitbucket/refined-bitbucket#385] opened 2020-10-13 00:21 UTC
Hey! Great project, using it for years and completely happy!

Except for the last week, when Refined started causing a full page refresh 🙀

I've traced the problem down to this function - https://github.com/refined-bitbucket/refined-bitbucket/blob/89e40530ebda863035dd31fd851c2050a4d2a833/src/ignore-whitespace/ignore-whitespace.js#L19

- you open a PR, it does not contain `?w=1`
- refined reloads the page with `?w=1
- full page reload 😭

as well as 

- you open a PR
- you click on a comment
- page updated with url without `?w=1`
- refined reloads the page with `?w=1
- full page reload 😭

**Comment by theKashey** [comment] 2020-10-13 00:24
![image](https://user-images.githubusercontent.com/582410/95801621-94c8ee00-0d46-11eb-840a-2a2f0ca554e1.png)
Look like this option has to be disabled. Ideally not by the user, which should now about advanced configuration.

**Comment by reyronald** [comment] 2020-10-13 11:25
Hey @theKashey , honestly that is kind of by design.

Originally that feature only made sure the links in the pull request list opened with the `?w=1` query parameter, but some users said that it wasn't enough and that they expected to never see a pull request with whitespace when this option on (see #306).

So the behavior in the first case looks as intended to me, but I couldn't reproduce the second one. Can you provide some more details? Are you using the new or old PR experience?

**Comment by theKashey** [comment] 2020-10-14 00:45
A very new experience. The problem hit me just this week, before it was working great.
The problem is more related that internal links no longer persist `?w` attribute and every second action triggers the `ignoreWhitespace` logic.

**Comment by raijinsetsu** [comment] 2020-10-14 18:13
I believe this was caused by the fix to using merge templates with the new UI. I noticed this issue started occurring after that version was pushed out. I'll have to dig up with original issue and PR but I vaguely remember that the change hooked into the browser navigation to detect URL changes.

**Comment by raijinsetsu** [comment] 2020-10-14 18:18
Issue #343 and PR #378 .

**Comment by mramos-dev** [comment] 2020-10-23 16:50
Having the 'Set "Ignore whitespace" ON by default in the Old PR Experience (already natively supported in the New PR experience)' option check seems to prevent the MERGE_COMMIT_TEMPLATE for functioning. Is this related to this reported issue?

**Comment by reyronald** [comment] 2020-11-07 19:12
I'll explicitly remove the ignore whitepace feature for the New UI since it's not needed there, but the full page refresh in the Old UI is necessary to achieve the feature's description since it's the only way load a PR with whitespaces off.

---

> Having the 'Set "Ignore whitespace" ON by default in the Old PR Experience (already natively supported in the New PR experience)' option check seems to prevent the MERGE_COMMIT_TEMPLATE for functioning. Is this related to this reported issue?

This is a separate issue. Will be resolved in the next release, thanks for pointing it out!

**Closed as completed** 2020-11-07 19:14 UTC
