### ISSUE TITLE
Pull request list view showing "undefined" overtop the branches button

### ISSUE THREAD

**Issue by btenny** [refined-bitbucket/refined-bitbucket#248] opened 2018-09-06 15:13 UTC
![image](https://user-images.githubusercontent.com/1723948/45168955-818fdf80-b1ca-11e8-9afe-be7aaae30661.png)

**Comment by reyronald** [comment] 2018-09-06 15:24
Duplicate of #240

**Closed as completed by reyronald** 2018-09-06 15:24 UTC
